import { useState } from "react";
import { useToast } from "./ToastContext";

export default function CreateCommerceModal({
  onClose,
    onCreated,
      categories = [],
        types = [],
          isDuplicate,
            API
            }) {
              const { addToast } = useToast();

                const [form, setForm] = useState({
                    name: "",
                        description: "",
                            category: "",
                                type: "",
                                    latitude: "",
                                        longitude: "",
                                            address: "",
                                                phone: "",
                                                    opening_hours: ""
                                                      });

                                                        const handleChange = (e) => {
                                                            setForm({ ...form, [e.target.name]: e.target.value });
                                                              };

                                                                const handleCreate = async () => {
                                                                    try {
                                                                          const lat = parseFloat(form.latitude);
                                                                                const lng = parseFloat(form.longitude);

                                                                                      if (isNaN(lat) || isNaN(lng)) {
                                                                                              addToast("❌ Coordonnées invalides", "error");
                                                                                                      return;
                                                                                                            }

                                                                                                                  if (isDuplicate(lat, lng)) {
                                                                                                                          addToast("❌ Commerce déjà à proximité", "error");
                                                                                                                                  return;
                                                                                                                                        }

                                                                                                                                              const dataToSend = {
                                                                                                                                                      ...form,
                                                                                                                                                              category: form.category ? parseInt(form.category) : null,
                                                                                                                                                                      type: form.type ? parseInt(form.type) : null,
                                                                                                                                                                              latitude: lat,
                                                                                                                                                                                      longitude: lng
                                                                                                                                                                                            };

                                                                                                                                                                                                  const res = await fetch(`${API}/commerces/`, {
                                                                                                                                                                                                          method: "POST",
                                                                                                                                                                                                                  headers: {
                                                                                                                                                                                                                            "Content-Type": "application/json"
                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                            body: JSON.stringify(dataToSend)
                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                        let result = {};
                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                      result = await res.json();
                                                                                                                                                                                                                                                                            } catch {}

                                                                                                                                                                                                                                                                                  if (!res.ok) {
                                                                                                                                                                                                                                                                                          addToast("❌ " + JSON.stringify(result), "error");
                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                              addToast("✅ Commerce créé", "success");

                                                                                                                                                                                                                                                                                                                    onCreated();
                                                                                                                                                                                                                                                                                                                          onClose();

                                                                                                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                                                                                                    console.error(err);
                                                                                                                                                                                                                                                                                                                                          addToast("❌ Erreur réseau", "error");
                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                      <div style={overlay}>
                                                                                                                                                                                                                                                                                                                                                            <div style={modal}>
                                                                                                                                                                                                                                                                                                                                                                    <h2>➕ Nouveau commerce</h2>

                                                                                                                                                                                                                                                                                                                                                                            <input name="name" onChange={handleChange} placeholder="Nom" />
                                                                                                                                                                                                                                                                                                                                                                                    <input name="description" onChange={handleChange} placeholder="Description" />

                                                                                                                                                                                                                                                                                                                                                                                            <select name="category" onChange={handleChange}>
                                                                                                                                                                                                                                                                                                                                                                                                      <option value="">-- Catégorie --</option>
                                                                                                                                                                                                                                                                                                                                                                                                                {categories.map((cat) => (
                                                                                                                                                                                                                                                                                                                                                                                                                            <option key={cat.id} value={cat.id}>{cat.name}</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      <select name="type" onChange={handleChange}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="">-- Type --</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {types.map((t) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option key={t.id} value={t.id}>{t.name}</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="latitude" onChange={handleChange} placeholder="Latitude" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input name="longitude" onChange={handleChange} placeholder="Longitude" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="address" onChange={handleChange} placeholder="Adresse" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input name="phone" onChange={handleChange} placeholder="Téléphone" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="opening_hours" onChange={handleChange} placeholder="Horaires" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: "flex", gap: 10, marginTop: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={handleCreate}>Créer</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={onClose}>Annuler</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const overlay = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  position: "fixed",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    top: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      left: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "rgba(0,0,0,0.5)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alignItems: "center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const modal = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: 350,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: 10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };