import { useState } from "react";
import { useToast } from "./ToastContext";

export default function DeleteConfirmModal({
  commerce,
    onClose,
      onDeleteSuccess,
        API,
        }) {

          const { addToast } = useToast();

            const [loading, setLoading] =
                useState(false);

                  if (!commerce) return null;

                    const handleDelete = async () => {

                        if (loading) return;

                            setLoading(true);

                                try {

                                      const res = await fetch(
                                              `${API}/commerces/${commerce.id}/delete/`,
                                                      {
                                                                method: "DELETE",
                                                                        }
                                                                              );

                                                                                    // ✅ DELETE SUCCESS
                                                                                          if (
                                                                                                  res.status === 200 ||
                                                                                                          res.status === 204
                                                                                                                ) {

                                                                                                                        addToast(
                                                                                                                                  "🗑️ Commerce supprimé",
                                                                                                                                            "success"
                                                                                                                                                    );

                                                                                                                                                            // 🔥 ferme le modal
                                                                                                                                                                    onClose();

                                                                                                                                                                            // 🔥 refresh instantané UI
                                                                                                                                                                                    onDeleteSuccess(commerce.id);

                                                                                                                                                                                            return;
                                                                                                                                                                                                  }

                                                                                                                                                                                                        let errorMsg =
                                                                                                                                                                                                                "❌ Erreur suppression";

                                                                                                                                                                                                                      try {

                                                                                                                                                                                                                              const data =
                                                                                                                                                                                                                                        await res.json();

                                                                                                                                                                                                                                                errorMsg =
                                                                                                                                                                                                                                                          "❌ " +
                                                                                                                                                                                                                                                                    JSON.stringify(data);

                                                                                                                                                                                                                                                                          } catch {}

                                                                                                                                                                                                                                                                                addToast(errorMsg, "error");

                                                                                                                                                                                                                                                                                    } catch (err) {

                                                                                                                                                                                                                                                                                          console.error(err);

                                                                                                                                                                                                                                                                                                // 🔥 backend déjà supprimé
                                                                                                                                                                                                                                                                                                      // mais fetch a crash
                                                                                                                                                                                                                                                                                                            onClose();

                                                                                                                                                                                                                                                                                                                  onDeleteSuccess(commerce.id);

                                                                                                                                                                                                                                                                                                                        addToast(
                                                                                                                                                                                                                                                                                                                                "🗑️ Commerce supprimé",
                                                                                                                                                                                                                                                                                                                                        "success"
                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                  } finally {

                                                                                                                                                                                                                                                                                                                                                        setLoading(false);
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                  position: "fixed",
                                                                                                                                                                                                                                                                                                                                                                                          top: 0,
                                                                                                                                                                                                                                                                                                                                                                                                  left: 0,
                                                                                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                  height: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                          background:
                                                                                                                                                                                                                                                                                                                                                                                                                                    "rgba(0,0,0,0.5)",
                                                                                                                                                                                                                                                                                                                                                                                                                                            display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: 320,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ⚠️ Confirmation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Supprimer{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <b>{commerce.name}</b> ?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gap: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    justifyContent:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={handleDelete}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: "red",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "10px 15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? "Suppression..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : "🗑️ Supprimer"}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "10px 15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ❌ Annuler

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }