import { useState } from "react";
import { useToast } from "./ToastContext";

export default function DeleteConfirmModal({
  commerce,
    onClose,
      onDeleted,
        API
        }) {

          const { addToast } = useToast();

            const [loading, setLoading] = useState(false);

              // 🔥 si aucun commerce sélectionné
                if (!commerce) return null;

                  const handleDelete = async () => {

                      // 🔥 évite double clic
                          if (loading) return;

                              setLoading(true);

                                  try {

                                        // 🔥 URL CORRIGÉE
                                              const res = await fetch(
                                                      `${API}/commerces/${commerce.id}/delete/`,
                                                              {
                                                                        method: "DELETE"
                                                                                }
                                                                                      );

                                                                                            // ✅ SUCCESS
                                                                                                  if (res.status === 204 || res.ok) {

                                                                                                          addToast("🗑️ Commerce supprimé", "success");

                                                                                                                  // 🔥 recharge la liste
                                                                                                                          onDeleted();

                                                                                                                                  // 🔥 ferme modal
                                                                                                                                          onClose();

                                                                                                                                                  return;
                                                                                                                                                        }

                                                                                                                                                              // ❌ ERREUR BACKEND
                                                                                                                                                                    let errorMsg = "❌ Erreur suppression";

                                                                                                                                                                          try {

                                                                                                                                                                                  const data = await res.json();

                                                                                                                                                                                          errorMsg = "❌ " + JSON.stringify(data);

                                                                                                                                                                                                } catch {}

                                                                                                                                                                                                      addToast(errorMsg, "error");

                                                                                                                                                                                                          } catch (err) {

                                                                                                                                                                                                                console.error(err);

                                                                                                                                                                                                                      addToast("❌ Erreur réseau", "error");

                                                                                                                                                                                                                          } finally {

                                                                                                                                                                                                                                // 🔥 reset loading
                                                                                                                                                                                                                                      setLoading(false);
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                              return (

                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                position: "fixed",
                                                                                                                                                                                                                                                                        top: 0,
                                                                                                                                                                                                                                                                                left: 0,
                                                                                                                                                                                                                                                                                        width: "100%",
                                                                                                                                                                                                                                                                                                height: "100%",
                                                                                                                                                                                                                                                                                                        background: "rgba(0,0,0,0.5)",
                                                                                                                                                                                                                                                                                                                display: "flex",
                                                                                                                                                                                                                                                                                                                        justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                alignItems: "center"
                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                          >

                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                  background: "#fff",
                                                                                                                                                                                                                                                                                                                                                                            padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                      width: 320,
                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                          textAlign: "center"
                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                        >

                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>⚠️ Confirmation</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  Supprimer <b>{commerce.name}</b> ?
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gap: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 15
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* 🔥 BOUTON DELETE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={handleDelete}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: "#f44336",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  opacity: loading ? 0.7 : 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? "Suppression..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : "🗑️ Supprimer"}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* 🔥 BOUTON CANCEL */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flex: 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ❌ Annuler

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }