import { useEffect, useState } from "react";
import { useToast } from "./ToastContext";

const API = "https://ideal-journey-jj6jxg9pwqqw3q6xj-8000.app.github.dev/api/commerces";

export default function EditCommerceModal({
  commerce,
    onClose,
      onUpdated,
        categories = [],
          types = [],
            isDuplicate // 🔥 AJOUT
            }) {
              const [form, setForm] = useState({});
                const { addToast } = useToast();

                  useEffect(() => {
                      if (commerce) {
                            setForm({
                                    name: commerce.name || "",
                                            description: commerce.description || "",
                                                    category: commerce.category?.id || "",
                                                            type: commerce.type?.id || "",
                                                                    latitude: commerce.latitude || "",
                                                                            longitude: commerce.longitude || "",
                                                                                    address: commerce.address || "",
                                                                                            phone: commerce.phone || "",
                                                                                                    opening_hours: commerce.opening_hours || ""
                                                                                                          });
                                                                                                              }
                                                                                                                }, [commerce]);

                                                                                                                  const handleChange = (e) => {
                                                                                                                      setForm({ ...form, [e.target.name]: e.target.value });
                                                                                                                        };

                                                                                                                          const handleUpdate = async () => {
                                                                                                                              try {
                                                                                                                                    const lat = parseFloat(form.latitude);
                                                                                                                                          const lng = parseFloat(form.longitude);

                                                                                                                                                if (isNaN(lat) || isNaN(lng)) {
                                                                                                                                                        addToast("❌ Coordonnées invalides", "error");
                                                                                                                                                                return;
                                                                                                                                                                      }

                                                                                                                                                                            // 🔥 CHECK DOUBLON
                                                                                                                                                                                  if (isDuplicate && isDuplicate(lat, lng, commerce.id)) {
                                                                                                                                                                                          addToast("❌ Commerce déjà à proximité", "error");
                                                                                                                                                                                                  return;
                                                                                                                                                                                                        }

                                                                                                                                                                                                              const dataToSend = {
                                                                                                                                                                                                                      ...form,
                                                                                                                                                                                                                              category: form.category ? parseInt(form.category) : null,
                                                                                                                                                                                                                                      type: form.type ? parseInt(form.type) : null,
                                                                                                                                                                                                                                              latitude: lat,
                                                                                                                                                                                                                                                      longitude: lng
                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                  const res = await fetch(`${API}/${commerce.id}/update/`, {
                                                                                                                                                                                                                                                                          method: "PATCH",
                                                                                                                                                                                                                                                                                  headers: {
                                                                                                                                                                                                                                                                                            "Content-Type": "application/json"
                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                            body: JSON.stringify(dataToSend)
                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                        // 🔥 SAFE JSON
                                                                                                                                                                                                                                                                                                                              let result = {};
                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                            result = await res.json();
                                                                                                                                                                                                                                                                                                                                                  } catch {}

                                                                                                                                                                                                                                                                                                                                                        if (!res.ok) {
                                                                                                                                                                                                                                                                                                                                                                addToast("❌ " + JSON.stringify(result), "error");
                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                    addToast("✅ Commerce modifié", "success");

                                                                                                                                                                                                                                                                                                                                                                                          onUpdated();
                                                                                                                                                                                                                                                                                                                                                                                                onClose();

                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                          console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                addToast("❌ Erreur réseau", "error");
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                        if (!commerce) return null;

                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                    position: "fixed",
                                                                                                                                                                                                                                                                                                                                                                                                                                          top: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                left: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            height: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: "rgba(0,0,0,0.5)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alignItems: "center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: 350,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: 10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>✏️ Modifier Commerce</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input name="name" value={form.name || ""} onChange={handleChange} placeholder="Nom" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="description" value={form.description || ""} onChange={handleChange} placeholder="Description" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* CATEGORY */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <select name="category" value={form.category || ""} onChange={handleChange}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="">-- Catégorie --</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {categories.map((cat) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option key={cat.id} value={cat.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {cat.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* TYPE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <select name="type" value={form.type || ""} onChange={handleChange}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="">-- Type --</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {types.map((t) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option key={t.id} value={t.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {t.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="latitude" value={form.latitude || ""} onChange={handleChange} placeholder="Latitude" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input name="longitude" value={form.longitude || ""} onChange={handleChange} placeholder="Longitude" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="address" value={form.address || ""} onChange={handleChange} placeholder="Adresse" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input name="phone" value={form.phone || ""} onChange={handleChange} placeholder="Téléphone" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="opening_hours" value={form.opening_hours || ""} onChange={handleChange} placeholder="Horaires" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ display: "flex", gap: 10, marginTop: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={handleUpdate} style={{ flex: 1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          💾 Sauvegarder
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={onClose} style={{ flex: 1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ❌ Fermer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }