export default function ToastContainer({ toasts, removeToast }) {
      return (
          <div
                style={{
                        display: "flex",
                                flexDirection: "column",
                                        gap: 10,
                                                marginTop: 10
                                                      }}
                                                          >
                                                                {toasts.map((toast) => (
                                                                        <div
                                                                                  key={toast.id}
                                                                                            style={{
                                                                                                        padding: "12px 16px",
                                                                                                                    borderRadius: 8,
                                                                                                                                color: "#fff",
                                                                                                                                            minWidth: 200,
                                                                                                                                                        background:
                                                                                                                                                                      toast.type === "success"
                                                                                                                                                                                      ? "#4CAF50"
                                                                                                                                                                                                      : toast.type === "error"
                                                                                                                                                                                                                      ? "#f44336"
                                                                                                                                                                                                                                      : "#333",
                                                                                                                                                                                                                                                  boxShadow: "0 4px 10px rgba(0,0,0,0.2)"
                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                              {toast.message}

                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                  marginTop: 5,
                                                                                                                                                                                                                                                                                                                                fontSize: 12,
                                                                                                                                                                                                                                                                                                                                              cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                            opacity: 0.7
                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => removeToast(toast.id)}
                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                          Fermer
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                    
