# Generated by Django 6.0.6 on 2026-06-15 19:03

import apps.commerces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.commerces.models.validate_phone_number]),
        ),
    ]
