import { useEffect, useState } from "react";
import EditCommerceModal from "./components/EditCommerceModal";
import CreateCommerceModal from "./components/CreateCommerceModal";
import ViewCommerceModal from "./components/ViewCommerceModal";
import DeleteConfirmModal from "./components/DeleteConfirmModal"; // 🔥 NEW
import { useToast } from "./components/ToastContext";
import ToastContainer from "./components/ToastContainer";

const API = "https://ideal-journey-jj6jxg9pwqqw3q6xj-8000.app.github.dev/api";

const MAX_DISTANCE = 20;

const getDistance = (lat1, lon1, lat2, lon2) => {
  const R = 6371000;
    const toRad = (x) => (x * Math.PI) / 180;

      const dLat = toRad(lat2 - lat1);
        const dLon = toRad(lon2 - lon1);

          const a =
              Math.sin(dLat / 2) ** 2 +
                  Math.cos(toRad(lat1)) *
                        Math.cos(toRad(lat2)) *
                              Math.sin(dLon / 2) ** 2;

                                return 2 * R * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
                                };

                                export default function App() {
                                  const [commerces, setCommerces] = useState([]);
                                    const [categories, setCategories] = useState([]);
                                      const [types, setTypes] = useState([]);

                                        const [selected, setSelected] = useState(null);
                                          const [selectedView, setSelectedView] = useState(null);
                                            const [selectedDelete, setSelectedDelete] = useState(null); // 🔥 NEW

                                              const [showCreate, setShowCreate] = useState(false);

                                                const { addToast, toasts, removeToast } = useToast();

                                                  const safeFetch = async (url) => {
                                                      const res = await fetch(url);
                                                          if (!res.ok) throw new Error("Erreur API");
                                                              return res.json();
                                                                };

                                                                  const load = async () => {
                                                                      try {
                                                                            const [c, cat, t] = await Promise.all([
                                                                                    safeFetch(`${API}/commerces/`),
                                                                                            safeFetch(`${API}/commerces/categories/`),
                                                                                                    safeFetch(`${API}/commerces/types/`)
                                                                                                          ]);

                                                                                                                setCommerces(c.results || c);
                                                                                                                      setCategories(cat);
                                                                                                                            setTypes(t);
                                                                                                                                } catch (err) {
                                                                                                                                      console.error(err);
                                                                                                                                            addToast("❌ Erreur chargement", "error");
                                                                                                                                                }
                                                                                                                                                  };

                                                                                                                                                    useEffect(() => {
                                                                                                                                                        load();
                                                                                                                                                          }, []);

                                                                                                                                                            const isDuplicate = (lat, lng, ignoreId = null) => {
                                                                                                                                                                return commerces.find(
                                                                                                                                                                      (c) =>
                                                                                                                                                                              (ignoreId ? c.id !== ignoreId : true) &&
                                                                                                                                                                                      getDistance(c.latitude, c.longitude, lat, lng) < MAX_DISTANCE
                                                                                                                                                                                          );
                                                                                                                                                                                            };

                                                                                                                                                                                              return (
                                                                                                                                                                                                  <div style={{ padding: 20, maxWidth: 600, margin: "0 auto" }}>
                                                                                                                                                                                                        <h1>🔥 Fubamaps</h1>

                                                                                                                                                                                                              {/* ➕ CREATE */}
                                                                                                                                                                                                                    <button onClick={() => setShowCreate(true)}>
                                                                                                                                                                                                                            ➕ Ajouter un commerce
                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                        <hr />

                                                                                                                                                                                                                                              <h3>Commerces</h3>

                                                                                                                                                                                                                                                    {/* 🔥 TOAST */}
                                                                                                                                                                                                                                                          <ToastContainer toasts={toasts} removeToast={removeToast} />

                                                                                                                                                                                                                                                                {commerces.map((c) => (
                                                                                                                                                                                                                                                                        <div key={c.id} style={{ marginBottom: 10 }}>
                                                                                                                                                                                                                                                                                  <b>{c.name}</b>

                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                        onClick={() => setSelectedView(c)}
                                                                                                                                                                                                                                                                                                                    style={{ marginLeft: 10 }}
                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                          👁 Voir
                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setSelected(c)}
                                                                                                                                                                                                                                                                                                                                                                                      style={{ marginLeft: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                            ✏️ Modifier
                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                {/* 🔥 DELETE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setSelectedDelete(c)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ marginLeft: 10, color: "red" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        🗑️ Supprimer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* ✏️ EDIT */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <EditCommerceModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    commerce={selected}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClose={() => setSelected(null)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onUpdated={load}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            categories={categories}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    types={types}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isDuplicate={isDuplicate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* ➕ CREATE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {showCreate && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <CreateCommerceModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClose={() => setShowCreate(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onCreated={load}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    categories={categories}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              types={types}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        isDuplicate={isDuplicate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  API={API}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* 👁 VIEW */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {selectedView && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ViewCommerceModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              commerce={selectedView}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClose={() => setSelectedView(null)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* 🗑️ DELETE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {selectedDelete && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <DeleteConfirmModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    commerce={selectedDelete}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClose={() => setSelectedDelete(null)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onDeleted={load}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  API={API}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }