# Generated by Django 6.0.3 on 2026-04-16 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commerces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "note",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "price_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Très cher"),
                            (2, "Cher"),
                            (3, "Normal"),
                            (4, "Bon marché"),
                            (5, "Très bon marché"),
                        ],
                        default=3,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("user_name", models.CharField(blank=True, max_length=100)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("dislikes", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_reported", models.BooleanField(default=False)),
                (
                    "commerce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avis",
                        to="commerces.commerce",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AvisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("fake", "Faux avis"),
                            ("abuse", "Contenu abusif"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "avis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="avis.avis",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="avis",
            index=models.Index(
                fields=["commerce"], name="avis_avis_commerc_77645b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avis",
            index=models.Index(fields=["note"], name="avis_avis_note_b68d14_idx"),
        ),
        migrations.AddIndex(
            model_name="avis",
            index=models.Index(
                fields=["price_rating"], name="avis_avis_price_r_0ba4ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avis",
            index=models.Index(
                fields=["created_at"], name="avis_avis_created_c1950e_idx"
            ),
        ),
    ]
